id: PF36B95FD
initial_creation_type: input
source_metadata:
  title: Songtsen Gampo Series
  language: en
  description: 'Texts by and about the seventh-century Tibetan emperor Songtsen Gampo
    (srong btsan sgam po, d. 650) during whose reign Buddhism first took root in Tibet:'
  volume:
    3d06f19838094cd18262f183c62dcab4:
      title: 'Self-Arising Wisdom: Songtsen Gampo Guru Sādhana'
      parent: Guru Yoga
created_at: '2022-03-01T01:38:32.544506'
last_modified_at: '2022-03-01T01:38:32.544512'
